services:
  antifraud-service:
    image: "${IMAGE_NAME}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ADMIN_EMAIL=admin@mail.ru
      - ADMIN_FULLNAME=Test Test
      - ADMIN_PASSWORD=123123123aA!
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/ping"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s
  antifraud-checker:
    image: "registry.prodcontest.com:443/2026-test-repos/backend/checker:${BACKEND_CHECKER_TAG}"
    environment:
      - ADMIN_EMAIL=admin@mail.ru
      - ADMIN_FULLNAME=Test Test
      - ADMIN_PASSWORD=123123123aA!
      - CONFIG_PATH=/app/configs/config.yaml
      - API_BASE_URL=http://antifraud-service:8080
      - API_TOKEN=test-token
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./reports:/report
    depends_on:
      postgres:
        condition: service_healthy
      antifraud-service:
        condition: service_healthy
  redis:
    image: redis:7-alpine
    container_name: antifraud-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  postgres:
    image: postgres:16-alpine
    container_name: antifraud-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: antifraud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d appdb -h 127.0.0.1 -p 5432" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:
  redis_data: