x-dnsfix: &dnsfix
  dns_search:
    - .
  dns_opt:
    - ndots:0
services:
  antifraud-service:
    <<: *dnsfix
    image: "${IMAGE_NAME}"
    networks: [isolated]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ADMIN_EMAIL=admin@mail.ru
      - ADMIN_FULLNAME=Test Test
      - ADMIN_PASSWORD=123123123aA!
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - RANDOM_SECRET=Jf/ZpZSxfMWnOexP48Mp1z200jd+8BVZ7ws6Uw5Jp/w=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/v1/ping"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s
  antifraud-checker:
    <<: *dnsfix
    image: "registry.prodcontest.com:443/2026-test-repos/backend/checker:${BACKEND_CHECKER_TAG}"
    networks: [isolated]
    environment:
      - ADMIN_EMAIL=admin@mail.ru
      - ADMIN_FULLNAME=Test Test
      - ADMIN_PASSWORD=123123123aA!
      - CONFIG_PATH=/app/configs/config.yaml
      - API_BASE_URL=http://antifraud-service:8080
      - API_TOKEN=test-token
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - RANDOM_SECRET=Jf/ZpZSxfMWnOexP48Mp1z200jd+8BVZ7ws6Uw5Jp/w=
      - PIPELINE_URL=${CI_PIPELINE_URL} 
      - JOB_ID=${CI_JOB_ID}
      - JOB_NAME=${CI_JOB_NAME}
    volumes:
      - ./reports:/report
    depends_on:
      postgres:
        condition: service_healthy
      antifraud-service:
        condition: service_healthy
  redis:
    <<: *dnsfix
    image: redis:7-alpine
    networks: [isolated]
    container_name: antifraud-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  postgres:
    <<: *dnsfix
    image: postgres:16-alpine
    networks: [isolated]
    container_name: antifraud-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d testdb -h 127.0.0.1 -p 5432" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
networks:
  isolated:
    internal: true
volumes:
  postgres_data:
  redis_data: